PUT http://localhost:3001/api/notes/63dfe198ac1bc87be00d98aa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2NiZjUzYmY1MmU5Yjk2YWY2ZjI5MSIsInVzZXJuYW1lIjoiZnJhaW5lcmFsZXgiLCJpYXQiOjE2NzUzNTgwMDcsImV4cCI6MTY3NTk2MjgwN30.3uv5Z_3treGniLOC_ckd1eiRuoKExdHcML3kGkQFMAE

{
"content": "Updating a note",
"isImportant": false
}